"""separa deteccion de atribucion e indexa claves foraneas

Revision ID: 26928f6d91e3
Revises: c9058fc55bde
Create Date: 2026-09-04 01:06:42.715414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26928f6d91e3'
down_revision: Union[str, Sequence[str], None] = 'c9058fc55bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_awareness_surveys_investigation_id'), 'awareness_surveys', ['investigation_id'], unique=False)
    op.add_column('entities', sa.Column('existence_confidence', sa.Float(), nullable=True))
    op.add_column('entities', sa.Column('identity_score', sa.Float(), nullable=True))
    op.add_column('entities', sa.Column('scorer_version', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_entities_investigation_id'), 'entities', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_identity_clusters_investigation_id'), 'identity_clusters', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_index(op.f('ix_investigations_target_id'), 'investigations', ['target_id'], unique=False)
    op.create_index(op.f('ix_relationships_investigation_id'), 'relationships', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_investigation_id'), table_name='relationships')
    op.drop_index(op.f('ix_investigations_target_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_identity_clusters_investigation_id'), table_name='identity_clusters')
    op.drop_index(op.f('ix_entities_investigation_id'), table_name='entities')
    op.drop_column('entities', 'scorer_version')
    op.drop_column('entities', 'identity_score')
    op.drop_column('entities', 'existence_confidence')
    op.drop_index(op.f('ix_awareness_surveys_investigation_id'), table_name='awareness_surveys')
    # ### end Alembic commands ###
